### ISSUE TITLE
ACTIVIDAD 9 NOTA INFORMATIVA 

### ISSUE THREAD

**Issue by YaelTrinidad** [SistemasTecTlaxiaco/actividad-9-nota-informativa-equipo-2#1]
[nota informativa.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-nota-informativa-equipo-2/files/9897653/nota.informativa.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De acuerdo a la rúbrica, has obtenido un 18.8% del 20%, debido a que en algunos párrafos no tienen coherencia, de igual forma no tratas de mejorar tu vocabulario

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
